#!/bin/bash

# Agent 5: Export Pipeline - LoRA → GGUF → Ollama
#
# This script takes a trained LoRA adapter and makes it usable in Ollama for benchmarking.
#
# Pipeline:
# 1. Merge LoRA weights with base model → Full model
# 2. Convert to GGUF format → Ollama-compatible
# 3. Create Modelfile → Ollama configuration
# 4. Import to Ollama → Ready for inference
#
# Why this matters:
# - LoRA adapters are small (~50MB) but can't run standalone
# - GGUF is a quantized format optimized for CPU/GPU inference
# - Ollama provides a simple API for our benchmark suite
#
# Time: ~30 seconds for Qwen2.5-0.5B

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Usage check
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <experiment-name>"
    echo "Example: $0 exp-001"
    exit 1
fi

EXPERIMENT_NAME=$1
EXPERIMENT_DIR="experiments/${EXPERIMENT_NAME}"
LORA_DIR="${EXPERIMENT_DIR}/lora"
MERGED_DIR="${EXPERIMENT_DIR}/merged"
GGUF_DIR="${EXPERIMENT_DIR}/gguf"

echo -e "${GREEN}[Agent 5] Starting export pipeline for ${EXPERIMENT_NAME}${NC}"

# Validate experiment exists
if [ ! -d "$LORA_DIR" ]; then
    echo -e "${RED}Error: LoRA model not found at ${LORA_DIR}${NC}"
    echo "Did you run training first?"
    exit 1
fi

# Step 1: Merge LoRA with base model
echo -e "${YELLOW}Step 1/4: Merging LoRA adapters with base model...${NC}"
python3 <<EOF
import os
from unsloth import FastLanguageModel
import torch

print("Loading base model...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen2.5-0.5B-Instruct",
    max_seq_length=2048,
    dtype=None,  # Auto-detect
    load_in_4bit=True,
)

print("Loading LoRA adapters from ${LORA_DIR}...")
model.load_adapter("${LORA_DIR}")

print("Merging weights...")
model = model.merge_and_unload()

print("Saving merged model to ${MERGED_DIR}...")
os.makedirs("${MERGED_DIR}", exist_ok=True)
model.save_pretrained("${MERGED_DIR}")
tokenizer.save_pretrained("${MERGED_DIR}")

print("✓ Merge complete!")
EOF

# Step 2: Convert to GGUF format
echo -e "${YELLOW}Step 2/4: Converting to GGUF format...${NC}"

# Check if llama.cpp converter is available
if ! command -v convert.py &> /dev/null && [ ! -f "scripts/convert.py" ]; then
    echo -e "${YELLOW}Installing llama.cpp converter...${NC}"

    # Clone llama.cpp if not present
    if [ ! -d "llama.cpp" ]; then
        git clone https://github.com/ggerganov/llama.cpp.git
    fi

    # Use llama.cpp's converter
    CONVERTER="python3 llama.cpp/convert.py"
else
    CONVERTER="python3 convert.py"
fi

# Convert to GGUF
mkdir -p "${GGUF_DIR}"
$CONVERTER "${MERGED_DIR}" \
    --outfile "${GGUF_DIR}/model.gguf" \
    --outtype q8_0  # 8-bit quantization (good quality/size tradeoff)

echo -e "✓ GGUF conversion complete!"

# Step 3: Create Modelfile for Ollama
echo -e "${YELLOW}Step 3/4: Creating Ollama Modelfile...${NC}"

cat > "${EXPERIMENT_DIR}/Modelfile" <<MODELFILE
# Modelfile for ${EXPERIMENT_NAME}
# Generated by export pipeline

FROM ${GGUF_DIR}/model.gguf

# Template (matches Qwen2.5 format)
TEMPLATE """{{ if .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}{{ if .Prompt }}<|im_start|>user
{{ .Prompt }}<|im_end|>
{{ end }}<|im_start|>assistant
"""

# Parameters optimized for consistent benchmarking
PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER top_k 40
PARAMETER repeat_penalty 1.1

# Stop tokens
PARAMETER stop "<|im_start|>"
PARAMETER stop "<|im_end|>"
PARAMETER stop "<|endoftext|>"

# System message
SYSTEM """You are a helpful AI assistant."""
MODELFILE

echo -e "✓ Modelfile created!"

# Step 4: Import to Ollama
echo -e "${YELLOW}Step 4/4: Importing to Ollama...${NC}"

# Check if Ollama is running
if ! docker ps | grep -q ollama; then
    echo -e "${RED}Error: Ollama container is not running${NC}"
    echo "Start it with: docker-compose up -d"
    exit 1
fi

# Create model in Ollama
docker exec ollama ollama create "${EXPERIMENT_NAME}" \
    -f "/experiments/${EXPERIMENT_NAME}/Modelfile"

echo -e "✓ Model imported to Ollama!"

# Verify model is available
echo -e "${YELLOW}Verifying model...${NC}"
if docker exec ollama ollama list | grep -q "${EXPERIMENT_NAME}"; then
    echo -e "${GREEN}✓ SUCCESS! Model '${EXPERIMENT_NAME}' is ready for benchmarking${NC}"

    # Test inference
    echo -e "\n${YELLOW}Quick test:${NC}"
    docker exec ollama ollama run "${EXPERIMENT_NAME}" "Hello! Respond in one sentence." --verbose
else
    echo -e "${RED}Error: Model not found in Ollama${NC}"
    exit 1
fi

echo -e "\n${GREEN}[Agent 5] Export pipeline complete!${NC}"
echo -e "Next step: Run benchmark with 'python benchmark/run.py ${EXPERIMENT_NAME}'"
